name: ci
on:
  pull_request:
    branches:
      - main
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: "lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5
      - uses: actions/setup-node@v6
        with:
          node-version: 26
          cache: "pnpm"
      - run: pnpm run lint
